version: 1.0.{build}
image: Visual Studio 2017
clone_depth: 1
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore --verbosity m
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet build
test:
  assemblies:
    only:
    - '**/AddressParser.Tests.dll'
artifacts:
- path: '**/AddressParser.*.nupkg'
test_script:
  # run the unit tests (requires changing into the test directory)
  - cmd: cd .\tests\AddressParser.Tests\
  - cmd: dotnet test
deploy: off